---
# Install docker
- name: install docker
  shell: curl https://releases.rancher.com/install-docker/19.03.sh | sh

- name: enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

# Users settings
- name: create rancher group
  group:
    name: rancher
    state: present

- name: create rancher user
  user:
    name: rancher
    group: rancher
    groups: docker

- name: visudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^rancher.*"
    line: "rancher  ALL=(ALL)  NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: generate ssh key
  local_action:
    module: openssh_keypair
    path: ./generated_files/id_rsa
    size: 2048

- name: generate ssh authorized_keys
  local_action:
    module: shell cat ./generated_files/id_rsa.pub > ./generated_files/authorized_keys

- name: mkdir root .ssh
  file:
    dest: /root/.ssh/
    state: directory
    owner: root
    group: root
    mode: 0700

- name: scp root ssh file
  copy:
    src: ./generated_files/id_rsa
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0600

- name: scp root ssh authorized_keys
  copy:
    src: ./generated_files/authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

- name: mkdir rancher .ssh
  file:
    dest: /home/rancher/.ssh/
    state: directory
    owner: rancher
    group: rancher
    mode: 0700

- name: scp rancher ssh file
  copy:
    src: ./generated_files/id_rsa
    dest: /home/rancher/.ssh/id_rsa
    owner: rancher
    group: rancher
    mode: 0600

- name: scp rancher ssh authorized_keys
  copy:
    src: ./generated_files/authorized_keys
    dest: /home/rancher/.ssh/authorized_keys
    owner: rancher
    group: rancher
    mode: 0600
