---
# OS settings
- name: yum update
  yum:
    name: "*"
    state: latest
  register: result

- set_fact:
    should_reboot: true
  when: result.changed == true

- name: set /etc/hostname
  template:
    src: ./hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  register: result

- set_fact:
    should_reboot: true
  when: result.changed == true

- name: set /etc/hosts
  lineinfile:
    path: /etc/hosts
    state: present
    regexp: "^127.0.0.1.*"
    line: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 {{ inventory_hostname_short }}"

- name: disable NetworkManager
  systemd:
    name: NetworkManager
    state: stopped
    enabled: no

- name: disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: set net.bridge.bridge-nf-call-iptables
  sysctl:
    name: "net.bridge.bridge-nf-call-iptables"
    value: "1"
    state: present
    ignoreerrors: yes
    reload: yes

- name: swapoff
  command: swapoff -a

- name: comment out fstab for swap
  replace:
    path: /etc/fstab
    regexp: "^(.*)swap(.*)$"
    replace: '# \1'

- name: restart machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  when: should_reboot == true
